/* Generated by Report Generator v3.16 (R2014a) */
var gHomeSys = "hdlcodercpu_eml:1";
var gNumSys = 12;
var gFrameID = {
"frameset_main":"hdlcodercpu_eml_CPU_Subsystem_8_bit_slwebview_main_frameset",
"explorer":"hdlcodercpu_eml_CPU_Subsystem_8_bit_slwebview_explorer",
"frameset_model":"hdlcodercpu_eml_CPU_Subsystem_8_bit_slwebview_frame",
"model":"hdlcodercpu_eml_CPU_Subsystem_8_bit_slwebview_model",
"web":"hdlcodercpu_eml_CPU_Subsystem_8_bit_slwebview_web"};
var gIDMap = {
"hdlcodercpu_eml:1":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"hdlcodercpu_eml:3":{"target":"slwebview_2.html","thumb":"slwebview_2_tb.png"},
"hdlcodercpu_eml:4":{"target":"slwebview_3.html","thumb":"slwebview_3_tb.png"},
"hdlcodercpu_eml:5":{"target":"slwebview_4.html","thumb":"slwebview_4_tb.png"},
"hdlcodercpu_eml:6":{"target":"slwebview_5.svg","thumb":"slwebview_5_tb.png"},
"hdlcodercpu_eml:8":{"target":"slwebview_6.html","thumb":"slwebview_6_tb.png"},
"hdlcodercpu_eml:9":{"target":"slwebview_7.html","thumb":"slwebview_7_tb.png"},
"hdlcodercpu_eml:10":{"target":"slwebview_8.html","thumb":"slwebview_8_tb.png"},
"hdlcodercpu_eml:11":{"target":"slwebview_9.html","thumb":"slwebview_9_tb.png"},
"hdlcodercpu_eml:13":{"target":"slwebview_10.html","thumb":"slwebview_10_tb.png"},
"hdlcodercpu_eml:21":{"target":"slwebview_11.html","thumb":"slwebview_11_tb.png"},
"hdlcodercpu_eml:6:526":{"target":"slwebview_12.svg","thumb":"slwebview_12_tb.png"}};

var gSLFcnId2SubsysId = {};