-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\hdlcodercpu_eml\CPU_Subsystem_8_bit_pkg.vhd
-- Created: 2014-08-26 11:41:14
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE CPU_Subsystem_8_bit_pkg IS
  TYPE vector_of_unsigned12 IS ARRAY (NATURAL RANGE <>) OF unsigned(11 DOWNTO 0);
END CPU_Subsystem_8_bit_pkg;

