-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\hdlcodercpu_eml\PC_Incrementer.vhd
-- Created: 2014-08-26 11:41:14
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PC_Incrementer
-- Source Path: hdlcodercpu_eml/CPU_Subsystem_8_bit/PC Incrementer
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PC_Incrementer IS
  PORT( jmp_offset                        :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        PC_current                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        PC_next                           :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END PC_Incrementer;


ARCHITECTURE rtl OF PC_Incrementer IS

  -- Signals
  SIGNAL jmp_offset_signed                : signed(7 DOWNTO 0);  -- int8
  SIGNAL PC_current_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL PC_next_tmp                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL add_cast                         : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL add_temp                         : signed(8 DOWNTO 0);  -- sfix9

BEGIN
  jmp_offset_signed <= signed(jmp_offset);

  PC_current_unsigned <= unsigned(PC_current);

  --MATLAB Function 'CPU_Subsystem_8_bit/PC Incrementer': '<S9>:1'
  -- PC incrementer increments the PC with jmp_offset
  -- HDL specific fimath
  --'<S9>:1:12'
  add_cast <= signed(resize(PC_current_unsigned, 9));
  add_temp <= resize(jmp_offset_signed, 9) + add_cast;
  PC_next_tmp <= unsigned(add_temp(7 DOWNTO 0));

  PC_next <= std_logic_vector(PC_next_tmp);

END rtl;

