-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\hdlcodercpu_eml\SinglePortRAM_256x8b.vhd
-- Created: 2014-08-26 11:41:14
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SinglePortRAM_256x8b
-- Source Path: hdlcodercpu_eml/CPU_Subsystem_8_bit/SinglePortRAM_Inst0/SinglePortRAM_256x8b
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SinglePortRAM_256x8b IS
  PORT( clk                               :   IN    std_logic;
        enb                               :   IN    std_logic;
        din                               :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        addr                              :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        we                                :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- int8
        );
END SinglePortRAM_256x8b;


ARCHITECTURE rtl OF SinglePortRAM_256x8b IS

  -- Local Type Definitions
  CONSTANT AddrWidth : INTEGER := 8;
  CONSTANT DataWidth : INTEGER := 8;
  TYPE ram_type IS ARRAY (2**AddrWidth - 1 DOWNTO 0) of std_logic_vector(DataWidth - 1 DOWNTO 0);

  -- Signals
  SIGNAL ram                              : ram_type := (OTHERS => (OTHERS => '0'));
  SIGNAL data_int                         : std_logic_vector(DataWidth - 1 DOWNTO 0) := (OTHERS => '0');
  SIGNAL addr_unsigned                    : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  addr_unsigned <= unsigned(addr);

  SinglePortRAM_256x8b_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        IF we = '1' THEN
          ram(to_integer(addr_unsigned)) <= din;
          data_int <= din;
        ELSE
          data_int <= ram(to_integer(addr_unsigned));
        END IF;
      END IF;
    END IF;
  END PROCESS SinglePortRAM_256x8b_process;

  dout <= data_int;

END rtl;

