-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\CPU_Subsystem_8_bit_pkg.vhd
-- Created: 2014-02-20 11:03:15
-- 
-- Generated by MATLAB 7.12 and Simulink HDL Coder 2.1
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE CPU_Subsystem_8_bit_pkg IS
  TYPE vector_of_unsigned12 IS ARRAY (NATURAL RANGE <>) OF unsigned(11 DOWNTO 0);
END CPU_Subsystem_8_bit_pkg;

