vlib work
vcom  CPU_Subsystem_8_bit_pkg.vhd
vcom  Accumulator.vhd
vcom  Arithmetic_Logical_Unit_8_bit.vhd
vcom  Control_Unit.vhd
vcom  Instruction_ROM.vhd
vcom  Instruction_Register.vhd
vcom  PC_Incrementer.vhd
vcom  Program_Counter.vhd
vcom  Shifter_8_bit.vhd
vcom  output_enable.vhd
vcom  RAM_256x8b_0.vhd
vcom  SinglePortRAM_Inst0.vhd
vcom  CPU_Subsystem_8_bit.vhd
