-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Program_Counter.vhd
-- Created: 2014-03-05 16:19:14
-- 
-- Generated by MATLAB 7.12 and Simulink HDL Coder 2.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Program_Counter
-- Source Path: hdlcodercpu_eml/CPU_Subsystem_8_bit/Program Counter
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Program_Counter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        func                              :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        addr_in                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        addr_out                          :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Program_Counter;


ARCHITECTURE rtl OF Program_Counter IS

  -- Signals
  SIGNAL func_unsigned                    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL addr_in_unsigned                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL addr_out_tmp                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL PC_value                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL PC_value_next                    : unsigned(7 DOWNTO 0);  -- ufix8

BEGIN
  func_unsigned <= unsigned(func);

  addr_in_unsigned <= unsigned(addr_in);

  Program_Counter_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      PC_value <= to_unsigned(0, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        PC_value <= PC_value_next;
      END IF;
    END IF;
  END PROCESS Program_Counter_1_process;

  Program_Counter_1_output : PROCESS (func_unsigned, addr_in_unsigned, PC_value)
  BEGIN
    PC_value_next <= PC_value;
    --MATLAB Function 'CPU_Subsystem_8_bit/Program Counter': '<S10>:1'
    -- Program Counter
    -- func = 0 => reset PC
    -- func = 1 => load PC
    -- func = 2 => increment PC
    -- HDL specific fimath
    --'<S10>:1:20'
    addr_out_tmp <= PC_value;

    CASE func_unsigned IS
      WHEN "00" =>
        -- reset
        --'<S10>:1:25'
        PC_value_next <= to_unsigned(0, 8);
      WHEN "01" =>
        -- store into PC
        --'<S10>:1:28'
        PC_value_next <= addr_in_unsigned;
      WHEN "10" =>
        -- increment PC
        --'<S10>:1:31'
        PC_value_next <= PC_value + 1;
      WHEN OTHERS => 
        NULL;
    END CASE;

  END PROCESS Program_Counter_1_output;


  addr_out <= std_logic_vector(addr_out_tmp);

END rtl;

